build:
    environment:
        php: '5.6.9'
    tests:
        override:
            -
                command: 'phpunit -c phpunit.xml.dist --coverage-clover=/home/scrutinizer/build/logs/clover.xml'
                coverage:
                    file: 'logs/clover.xml'
                    format: 'clover'
filter:
    paths: [src/*]
    excluded_paths: [vendor/*]
before_commands:
    - 'composer install --prefer-source'
tools:
    external_code_coverage:
        timeout: 300
    php_code_sniffer: true
    php_cpd:
        enabled: true
        excluded_dirs: [vendor]
    php_pdepend:
        enabled: true
        excluded_dirs: [vendor]
    php_loc:
        enabled: true
        excluded_dirs: [vendor]
    php_hhvm: false
    php_mess_detector: true
    php_analyzer: true
changetracking:
    bug_patterns: ["\bfix(?:es|ed)?\b"]
    feature_patterns: ["\badd(?:s|ed)?\b", "\bimplement(?:s|ed)?\b", "\bresolve(?:s|d)?\b"]
