preset: psr2

risky: false

enabled:
  - align_double_arrow
  - align_equals
  - alpha_ordered_imports
  - blank_line_before_return
  - cast_spaces
  - combine_consecutive_unsets
  - concat_with_spaces
  - function_typehint_space
  - hash_to_slash_comment
  - linebreak_after_opening_tag
  - lowercase_cast
  - method_separation
  - no_blank_lines_after_class_opening
  - no_blank_lines_after_phpdoc
  - no_blank_lines_after_return
  - no_blank_lines_after_throw
  - no_blank_lines_before_namespace
  - no_empty_comment
  - no_empty_phpdoc
  - no_empty_statement
  - no_extra_consecutive_blank_lines
  - no_leading_import_slash
  - no_leading_namespace_whitespace
  - no_multiline_whitespace_around_double_arrow
  - no_multiline_whitespace_before_semicolons
  - no_trailing_comma_in_singleline_array
  - no_unneeded_control_parentheses
  - no_unreachable_default_argument_value
  - no_unused_imports
  - no_useless_else
  - no_useless_return
  - no_whitespace_before_comma_in_array
  - object_operator_without_whitespace
  - ordered_class_elements
  - phpdoc_add_missing_param_annotation
  - phpdoc_align
  - phpdoc_indent
  - phpdoc_inline_tag
  - phpdoc_link_to_see
  - phpdoc_no_access
  - phpdoc_no_empty_return
  - phpdoc_order
  - phpdoc_property
  - phpdoc_scalar
  - phpdoc_separation
  - phpdoc_single_line_var_spacing
  - phpdoc_summary
  - phpdoc_to_comment
  - phpdoc_trim
  - phpdoc_type_to_var
  - phpdoc_types
  - return_type_declaration
  - self_accessor
  - semicolon_after_instruction
  - short_array_syntax
  - short_scalar_cast
  - single_quote
  - space_after_semicolon
  - standardize_not_equals
  - ternary_operator_spaces
  - trailing_comma_in_multiline_array
  - trim_array_spaces
  - whitespace_after_comma_in_array

finder:
  exclude:
    - "docs"
    - "tests"
    - "travis"
    - "vendor"
  name:
    - "*.php"